# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KeyRotator < Formula
  desc ""
  homepage ""
  version "0.1.0-beta1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucasmelin/key-rotator/releases/download/v0.1.0-beta1/key-rotator_0.1.0-beta1_darwin_amd64.tar.gz"
      sha256 "32e83b6e4be54a3f22a5e8f717ae6c255268b5edc00621af7659fd3a74607745"

      def install
        bin.install "key-rotator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucasmelin/key-rotator/releases/download/v0.1.0-beta1/key-rotator_0.1.0-beta1_darwin_arm64.tar.gz"
      sha256 "381831ad8482b6e81c2146a0aa4cc8644013eb7194e48bbc5bcbe5a027238ab0"

      def install
        bin.install "key-rotator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lucasmelin/key-rotator/releases/download/v0.1.0-beta1/key-rotator_0.1.0-beta1_linux_amd64.tar.gz"
        sha256 "f29404785994a81852399e9a238f32cca1aa575e7ab0476e44761f372f59fe38"

        def install
          bin.install "key-rotator"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/lucasmelin/key-rotator/releases/download/v0.1.0-beta1/key-rotator_0.1.0-beta1_linux_armv6.tar.gz"
        sha256 "c938491b7b141f9d7734d05b46bdc3b39831e19c9a38d4453aeb3c98d81586a7"

        def install
          bin.install "key-rotator"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lucasmelin/key-rotator/releases/download/v0.1.0-beta1/key-rotator_0.1.0-beta1_linux_arm64.tar.gz"
        sha256 "1589242793e0981114f7d4830d65a96b799af81efbe7da91a527f448d9130a15"

        def install
          bin.install "key-rotator"
        end
      end
    end
  end
end
